all:
	clang++ -o main main.cpp "../common/shader.cpp" -std=c++11 -stdlib=libc++ -lglfw -lglew -framework OpenGL

run:
	clang++ -o main main.cpp "../common/shader.cpp" -std=c++11 -stdlib=libc++ -lglfw -lglew -framework OpenGL
	./main

clean:
	rm main